name: Release Builds

on:
  push:
    tags:
      - "*.*.*"

permissions: read-all

jobs:
  Release:
    name: "${{ matrix.name }}"
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix:
        include:
          - {name: linux-x86_64,      os: macos-latest}
          - {name: linux-x86_64-musl, os: macos-latest}
          - {name: windows-x86_64,    os: macos-latest}
          - {name: macos-aarch64,     os: macos-latest}
          - {name: macos-x86_64,      os: macos-13}
    permissions:
      contents: write
    runs-on: "${{ matrix.os }}"
    env:
      MRUBY_CONFIG: config/config-${{ matrix.name }}.rb
    steps:
      - run: brew install --force automake autoconf libtool mingw-w64 zig
      - uses: actions/checkout@v4
        name: "Checkout ${{ github.ref_name }} MRuby"
        with:
          repository: mruby/mruby
          path: mruby
          ref: ${{ github.ref_name }}
      - uses: actions/checkout@v4
        name: "Checkout ${{ github.ref_name }} ( ${{ github.sha }} )"
        with:
          path: config
      - name: Builds
        run: rake -f mruby/Rakefile
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ contains(github.ref_name, '-rc') }}
          files: mruby/build/${{ matrix.name }}/mruby-*.zip
          # draft: true
          # body_path: NEWS
